name: Bug report
description: Report a reproducible problem in Qryvanta
title: "bug: "
labels:
  - bug
body:
  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: What happened and what did you expect?
      placeholder: Clear and concise description of the bug.
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      description: Provide exact steps so maintainers can reproduce quickly.
      placeholder: |
        1. Run ...
        2. Open ...
        3. Observe ...
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: OS, Rust version, Node version, pnpm version, and commit hash.
      placeholder: macOS 14, rustc 1.xx, node 22.x, pnpm 10.x, commit abc123
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Logs and screenshots
      description: Paste relevant logs, stack traces, or screenshots.
      render: shell
