name: Semgrep
on:
    workflow_dispatch: {}
    schedule:
        # Run once per day instead of on every push or pull request.
        - cron: "12 15 * * *"
jobs:
    semgrep:
        name: semgrep/ci
        runs-on: ubuntu-latest
        permissions:
            contents: read
        env:
            SEMGREP_APP_TOKEN: ${{ secrets.SEMGREP_APP_TOKEN }}
        container:
            image: semgrep/semgrep
        if: (github.actor != 'dependabot[bot]')
        steps:
            - uses: actions/checkout@v4
            - run: semgrep ci
