ALTER TABLE entity_fields
    ADD COLUMN IF NOT EXISTS description TEXT,
    ADD COLUMN IF NOT EXISTS max_length INTEGER,
    ADD COLUMN IF NOT EXISTS min_value DOUBLE PRECISION,
    ADD COLUMN IF NOT EXISTS max_value DOUBLE PRECISION;
